# Generated by Django 5.1.2 on 2024-10-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregator',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarCondition',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarDrive',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.country')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.country')),
            ],
        ),
        migrations.CreateModel(
            name='CarAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField(unique=True)),
                ('link', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('production_date', models.IntegerField()),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('engine_capacity', models.FloatField(blank=True, null=True)),
                ('title', models.TextField(max_length=400)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('images', models.JSONField()),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('price_history', models.JSONField()),
                ('aggregator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.aggregator')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.area')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.brand')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.carcondition')),
                ('cars_drive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.cardrive')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.carmodel')),
                ('cars_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.cartype')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.color')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.country')),
                ('cars_engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.engine')),
                ('cars_gearbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.gearbox')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.region')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.region'),
        ),
    ]
